kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafanadb-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
